general {
    lock_cmd = pidof hyprlock || hyprlock
}

# Turn off screen
listener {
    timeout = 300
    on-timeout = ; hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock screen ten seconds later
listener {
    timeout = 310
    on-timeout = loginctl lock-session
}
