# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
  ignore_empty_input = true
}

# BACKGROUND
background {
  path = screenshot
  blur_size = 2
  blur_passes = 1
}

# INPUT FIELD
input-field {
  monitor =
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.5
  dots_center = true
  dots_rounding = -1
  inner_color = rgb(36, 39, 58)
  font_color = rgb(202, 211, 245)
  fade_on_empty = true
  fade_timeout = 1000
  placeholder_text = 
  hide_input = false
  rounding = -1
  check_color = rgb(245, 169, 127)
  fail_color = rgb(237, 135, 150)
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  fail_timeout = 2000
  fail_transition = 300
  capslock_color = -1
  numlock_color = -1
  bothlock_color = -1
  invert_numlock = true
  swap_font_color = true

  size = 800, 50
  position = 0, 200
  valign = bottom
}

# CLOCK
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M") </big></b>"
    color = rgb(183, 189, 248)
    font_size = 94
    font_family = JetBrains Mono Nerd Font 10

    position = 0, -100
    halign = center
    valign = top
}

# USERNAME
label {
    monitor =
    text = $USER
    color = rgb(198, 160, 246)
    font_size = 18
    font_family = JetBrains Mono Nerd Font 10

    position = 0, -250
    halign = center
    valign = top
}
