# luna monitors
monitor = eDP-1, 1920x1080@60, 0x0, 1

# terra monitors
monitor = DP-1, 2560x1440@165, 0x0, 1
monitor = DP-2, 2560x1440@165, 2560x0, 1

# default monitor config
monitor=,preferred,auto,auto

